AllCops:
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
  DisplayCopNames: true

Style/FileName:
  Enabled: false

Style/Documentation:
  Enabled: true
  Exclude:
    - 'lib/formatter/number/version.rb'
    - 'test/**/*'

Metrics/LineLength:
  Max: 82

# Method
Style/SingleLineMethods:
  AllowIfMethodIsEmpty: false

Style/FormatString:
  EnforcedStyle: percent

# Brackets
Style/SpaceInsideBrackets:
  Enabled: false

# Hash
Style/IndentHash:
  EnforcedStyle: consistent

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: space

# Parameter
Metrics/ParameterLists:
  Max: 3
  CountKeywordArgs: true
